### ISSUE TITLE
How to integrate with angualr 2

### ISSUE THREAD

**Issue by krushnachandra** [Pushwoosh/web-push-notifications-sample#1]

**Comment by wfhm** [comment]
Hey,

1. First, you need to create the following files in your project:

**/src/pushwoosh-service-worker.js
/src/manifest.json**

Put the following line in **pushwoosh-service-worker.js**:

```
importScripts('https://cdn.pushwoosh.com/webpush/v3/pushwoosh-service-worker.js')
```

And the following code in **manifest.json**:

```
{
  "name": "App Name",
  "short_name": "Short App Name",
  "display": "standalone",
  "gcm_sender_id": "GCM_SENDER_ID",
  "gcm_user_visible_only": true
}
```

2. Find assets config in your angular.json:

architect -> build -> options -> assets

Add paths to the created files:

    "src/pushwoosh-service-worker.js",
    "src/manifest.json"

3. Add manifest.json to <head> in your index.html:

```
<link rel="manifest" href="manifest.json">
```

4. Follow npm installation guide:

https://www.pushwoosh.com/v1.0/docs/web-push-sdk-30#section-install-from-npm

Alternatively, you can use index.html to install SDK via CDN:

https://www.pushwoosh.com/v1.0/docs/web-push-sdk-30#section-integration
